// Offline topo basemap style (OpenMapTiles vector schema).
//
// Builds a MapLibre StyleSpecification that renders the statewide Colorado
// vector tiles (generated by Planetiler in the OpenMapTiles schema) into a
// readable, field-friendly topo map: land/water, roads with casings, admin
// boundaries, mountain peaks, and place/road labels.
//
// Everything is OFFLINE: the vector source and the glyph fonts are local files
// on the device, so there are NO network requests. The two device-specific
// paths (the .mbtiles vector source and the glyph fonts directory) are injected
// at runtime, since they only exist once the base map is sideloaded onto the
// phone.
//
// Labels use the "Noto Sans Regular" font stack — the one stack we ship offline
// (tiles/fonts/Noto Sans Regular). Do NOT reference any other font name here, or
// MapLibre will fail to find glyphs and drop the labels.

import type { StyleSpecification } from '@maplibre/maplibre-react-native'

const FONT = ['Noto Sans Regular']

// Source id the layers below reference. Kept in one place so it can't drift.
export const TOPO_SOURCE = 'openmaptiles'

/** Build the offline topo style.
 *  @param vectorTilesUrl  mbtiles:// URL for the sideloaded colorado.mbtiles
 *  @param glyphsUrl       local glyphs template, e.g. file://.../fonts/{fontstack}/{range}.pbf
 */
/** Optional per-trip shaded relief, rendered UNDER the topo features so terrain
 *  shows through while roads/labels stay on top. Only covers the trip footprint. */
export interface HillshadeLayer {
  url: string
  tileSize: number
  minzoom: number
  maxzoom: number
}

export function buildTopoStyle(
  vectorTilesUrl: string,
  glyphsUrl: string,
  hillshade?: HillshadeLayer | null,
): StyleSpecification {
  return {
    version: 8,
    glyphs: glyphsUrl,
    sources: {
      [TOPO_SOURCE]: {
        type: 'vector',
        tiles: [vectorTilesUrl],
        // OpenMapTiles tops out at z14; allow overzoom above that so roads stay
        // visible when zoomed in past the deepest tile.
        minzoom: 0,
        maxzoom: 14,
      },
      // Per-trip shaded relief (only present where the trip footprint covers).
      ...(hillshade
        ? {
            hillshade: {
              type: 'raster' as const,
              tiles: [hillshade.url],
              tileSize: hillshade.tileSize,
              minzoom: hillshade.minzoom,
              maxzoom: hillshade.maxzoom,
            },
          }
        : {}),
    },
    layers: [
      // --- Base paper ---------------------------------------------------------
      { id: 'background', type: 'background', paint: { 'background-color': '#f6f2e9' } },
      // --- Shaded relief: above the paper, below all topo features ------------
      ...(hillshade
        ? [{ id: 'hillshade', type: 'raster' as const, source: 'hillshade', paint: { 'raster-opacity': 0.55 } }]
        : []),

      // --- Land cover & landuse ----------------------------------------------
      {
        id: 'landcover-wood',
        type: 'fill',
        source: TOPO_SOURCE,
        'source-layer': 'landcover',
        filter: ['==', ['get', 'class'], 'wood'],
        paint: { 'fill-color': '#cfe0c3', 'fill-opacity': 0.6 },
      },
      {
        id: 'landcover-grass',
        type: 'fill',
        source: TOPO_SOURCE,
        'source-layer': 'landcover',
        filter: ['in', ['get', 'class'], ['literal', ['grass', 'scrub', 'heath']]],
        paint: { 'fill-color': '#dce7cb', 'fill-opacity': 0.5 },
      },
      {
        id: 'landuse-park',
        type: 'fill',
        source: TOPO_SOURCE,
        'source-layer': 'park',
        paint: { 'fill-color': '#d6e8cc', 'fill-opacity': 0.5 },
      },

      // --- Water --------------------------------------------------------------
      {
        id: 'water',
        type: 'fill',
        source: TOPO_SOURCE,
        'source-layer': 'water',
        paint: { 'fill-color': '#a5cfe3' },
      },
      {
        id: 'waterway',
        type: 'line',
        source: TOPO_SOURCE,
        'source-layer': 'waterway',
        // Deeper, wider blue than a default basemap: thin pale lines vanished
        // under the 60%-opacity score cells, so creeks/streams read clearly now.
        paint: {
          'line-color': '#3d7ea6',
          'line-width': ['interpolate', ['linear'], ['zoom'], 8, 1, 12, 2.2, 16, 4.5],
        },
      },

      // --- Roads: casings first (drawn under), then fills ---------------------
      {
        id: 'road-casing',
        type: 'line',
        source: TOPO_SOURCE,
        'source-layer': 'transportation',
        filter: ['in', ['get', 'class'], ['literal', ['motorway', 'trunk', 'primary', 'secondary', 'tertiary']]],
        layout: { 'line-cap': 'round', 'line-join': 'round' },
        paint: {
          'line-color': '#c9a24b',
          'line-width': ['interpolate', ['linear'], ['zoom'], 7, 1.5, 12, 6, 16, 14],
        },
      },
      {
        id: 'road-major',
        type: 'line',
        source: TOPO_SOURCE,
        'source-layer': 'transportation',
        filter: ['in', ['get', 'class'], ['literal', ['motorway', 'trunk', 'primary', 'secondary', 'tertiary']]],
        layout: { 'line-cap': 'round', 'line-join': 'round' },
        paint: {
          'line-color': '#fff6df',
          'line-width': ['interpolate', ['linear'], ['zoom'], 7, 0.5, 12, 4, 16, 11],
        },
      },
      {
        id: 'road-minor',
        type: 'line',
        source: TOPO_SOURCE,
        'source-layer': 'transportation',
        filter: ['in', ['get', 'class'], ['literal', ['minor', 'service']]],
        minzoom: 12,
        layout: { 'line-cap': 'round', 'line-join': 'round' },
        paint: {
          'line-color': '#ffffff',
          'line-width': ['interpolate', ['linear'], ['zoom'], 12, 0.5, 16, 5],
        },
      },
      // Trails/tracks — important for prospecting access; dashed brown.
      {
        id: 'road-path',
        type: 'line',
        source: TOPO_SOURCE,
        'source-layer': 'transportation',
        filter: ['in', ['get', 'class'], ['literal', ['path', 'track', 'pedestrian']]],
        minzoom: 12,
        paint: {
          'line-color': '#9c6b3f',
          'line-width': ['interpolate', ['linear'], ['zoom'], 12, 0.6, 16, 2],
          'line-dasharray': [2, 2],
        },
      },
      {
        id: 'rail',
        type: 'line',
        source: TOPO_SOURCE,
        'source-layer': 'transportation',
        filter: ['==', ['get', 'class'], 'rail'],
        minzoom: 11,
        paint: { 'line-color': '#9a9a9a', 'line-width': ['interpolate', ['linear'], ['zoom'], 11, 0.5, 16, 1.5] },
      },

      // --- Admin boundaries ---------------------------------------------------
      {
        id: 'boundary-admin',
        type: 'line',
        source: TOPO_SOURCE,
        'source-layer': 'boundary',
        filter: ['<=', ['get', 'admin_level'], 6],
        paint: {
          'line-color': '#9b8bb0',
          'line-width': ['interpolate', ['linear'], ['zoom'], 4, 0.5, 10, 1.5],
          'line-dasharray': [3, 2],
        },
      },

      // --- Labels -------------------------------------------------------------
      // Mountain peaks: genuinely useful context for backcountry prospecting.
      {
        id: 'peak-label',
        type: 'symbol',
        source: TOPO_SOURCE,
        'source-layer': 'mountain_peak',
        minzoom: 11,
        layout: {
          'text-field': ['coalesce', ['get', 'name'], ''],
          'text-font': FONT,
          'text-size': 11,
          'text-offset': [0, 0.6],
          'text-anchor': 'top',
        },
        paint: { 'text-color': '#6b5a3e', 'text-halo-color': '#f6f2e9', 'text-halo-width': 1.2 },
      },
      {
        id: 'road-label',
        type: 'symbol',
        source: TOPO_SOURCE,
        'source-layer': 'transportation_name',
        minzoom: 13,
        layout: {
          'symbol-placement': 'line',
          'text-field': ['coalesce', ['get', 'name'], ''],
          'text-font': FONT,
          'text-size': 11,
        },
        paint: { 'text-color': '#5a5346', 'text-halo-color': '#ffffff', 'text-halo-width': 1.2 },
      },
      {
        id: 'place-label',
        type: 'symbol',
        source: TOPO_SOURCE,
        'source-layer': 'place',
        filter: ['in', ['get', 'class'], ['literal', ['city', 'town', 'village', 'hamlet']]],
        layout: {
          'text-field': ['coalesce', ['get', 'name'], ''],
          'text-font': FONT,
          'text-size': ['interpolate', ['linear'], ['zoom'], 6, 11, 12, 16],
        },
        paint: { 'text-color': '#3a3530', 'text-halo-color': '#f6f2e9', 'text-halo-width': 1.5 },
      },
    ],
  } as StyleSpecification
}
